name: fedml
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.12
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - openpyxl
  - flask
  - requests
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - opacus
      - absl-py