name: fedml
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - cpuonly
  - openpyxl
  - pip
  - pip:
    - matplotlib==3.8.0
    - opacus==1.1.1
    - absl-py==2.0.0
    - scipy==1.11.3
    - scikit-learn==1.3.0
    - flask
    - pandas